catalog:
  '@antfu/ni': ^25.0.0
  '@iconify-json/carbon': ^1.2.10
  '@types/lodash-es': ^4.17.12
  '@types/node': ^22.16.0
  '@unocss/preset-legacy-compat': ^66.3.3
  '@vitejs/plugin-vue': ^6.0.0
  '@vue/runtime-core': ^3.5.17
  '@vueuse/core': ^13.5.0
  '@xiaohe01/eslint-config': ^1.9.1
  '@xiaohe01/stylelint-config': ^2.4.0
  '@xiaohe01/tsconfig': ^2.0.0
  await-to-js: ^3.0.0
  dayjs: ^1.11.13
  eslint: ^9.30.1
  esno: ^4.8.0
  husky: ^9.1.7
  lint-staged: ^16.1.2
  lodash-es: ^4.17.21
  ress: ^5.0.2
  stylelint: ^16.21.1
  terser: ^5.43.1
  typescript: ~5.8.3
  unocss: ^66.3.3
  unplugin-auto-import: ^19.3.0
  unplugin-vue-components: ^28.8.0
  vite: ^7.0.2
  vue: ^3.5.17
  vue-tsc: ^3.0.1
onlyBuiltDependencies:
  - esbuild