catalog:
  "@antfu/ni": ^27.0.1
  "@iconify-json/carbon": ^1.2.14
  "@types/lodash-es": ^4.17.12
  "@types/node": ^22.19.1
  "@unocss/preset-legacy-compat": ^66.5.7
  "@vitejs/plugin-vue": ^6.0.2
  "@vue/runtime-core": ^3.5.24
  "@vueuse/core": ^14.0.0
  "@xiaohe01/eslint-config": ^4.0.0
  "@xiaohe01/stylelint-config": ^3.0.0
  "@xiaohe01/tsconfig": ^3.0.0
  await-to-js: ^3.0.0
  dayjs: ^1.11.19
  eslint: ^9.39.1
  esno: ^4.8.0
  husky: ^9.1.7
  lint-staged: ^16.2.6
  lodash-es: ^4.17.21
  ress: ^5.0.2
  stylelint: ^16.25.0
  terser: ^5.44.1
  typescript: ~5.9.3
  unocss: ^66.5.7
  unplugin-auto-import: ^20.2.0
  unplugin-vue-components: ^30.0.0
  vite: ^7.2.2
  vue: ^3.5.24
  vue-tsc: ^3.1.4
onlyBuiltDependencies:
  - esbuild