catalogMode: prefer
shellEmulator: true

catalog:
  "@antfu/ni": ^28.0.0
  "@iconify-json/carbon": ^1.2.15
  "@types/lodash-es": ^4.17.12
  "@types/node": ^22.19.3
  "@unocss/preset-legacy-compat": ^66.5.11
  "@vitejs/plugin-vue": ^6.0.3
  "@vue/runtime-core": ^3.5.26
  "@vueuse/core": ^14.1.0
  "@xiaohe01/eslint-config": ^4.1.0
  "@xiaohe01/stylelint-config": ^3.1.0
  "@xiaohe01/tsconfig": ^3.1.0
  await-to-js: ^3.0.0
  dayjs: ^1.11.19
  eslint: ^9.39.2
  esno: ^4.8.0
  husky: ^9.1.7
  lint-staged: ^16.2.7
  lodash-es: ^4.17.22
  ress: ^5.0.2
  stylelint: ^16.26.1
  terser: ^5.44.1
  typescript: ~5.9.3
  unocss: ^66.5.11
  unplugin-auto-import: ^20.3.0
  unplugin-vue-components: ^30.0.0
  vite: ^7.3.0
  vue: ^3.5.26
  vue-tsc: ^3.2.1

onlyBuiltDependencies:
  - esbuild